#set working directory
setwd("C:/Users/cherukuri/Desktop/GA_projects/microbiome/nick_data/")
####Species######
species<- as.matrix(read.delim2("species_abundance.txt"))
total_hardness<- as.matrix(read.delim2("factors.txt"))
#install.packages("Hmisc")
library(Hmisc)
calc_corr <- rcorr(species,total_hardness, type= "spearman")
calc_corr_value <- as.matrix(calc_corr$r)
calc_p_value<- as.matrix(calc_corr$P)
corr_value<- print(calc_corr_value[1:1687,1687:1704])
p_value<-print(calc_p_value[1:1688,1688:1704])
final<-cbind(corr_value,p_value)
write.table(final,file="species_corr_matrix_allfactors.txt",row.names = T,col.names = T,quote = F,sep = "\t")
#### order#####
order<- as.matrix(read.delim2("order_abundance.txt"))
total_hardness<- as.matrix(read.delim2("factors.txt"))
#install.packages("Hmisc")
library(Hmisc)
calc_corr <- rcorr(order,total_hardness, type= "spearman")
calc_corr_value <- as.matrix(calc_corr$r)
calc_p_value<- as.matrix(calc_corr$P)
corr_value<- print(calc_corr_value[1:126,127:143])
p_value<-print(calc_p_value[1:126,127:143])
final<-cbind(corr_value,p_value)
write.table(final,file="order_corr_matrix_allfactors.txt",row.names = T,col.names = T,quote = F,sep = "\t")
matrix<-read.table("order_corr_matrix_allfactors.txt")
